# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
   configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  apt_packages:
    - build-essential
  jobs:
    install:
      - pip install cython==3.0.0
      - pip install matplotlib==3.9.3 numpy==2.1.3 pandas==2.2.3 scikit-learn==1.6.0 scipy==1.14.1 setuptools==72.1.0
      - pip install -r docs/requirements.txt
      - pip install sphinx-rtd-theme

python:
   install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
