# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
   configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - build-essential
  jobs:
    install:
      - pip install cython==3.0.0
      - pip install -r docs/requirements.txt

python:
   install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
