name: aligater
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies: 
  - python==3.11.10 slack
  - pip:
      - cython==3.0.0
      - matplotlib==3.9.3
      - numpy==2.1.3
      - pandas==2.2.3
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - setuptools==72.1.0

